#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <windows.h>
#include "sodium.h"
#include "archive.h"
#include "signing.h"

#define PATH_SIZE 4096
#define KEY_ID_SIZE 65

static int join(char* out, size_t size, const char* a, const char* b) { int n = snprintf(out, size, "%s%s%s", a, a[strlen(a)-1] == '\\' ? "" : "\\", b); return n >= 0 && (size_t)n < size; }
static int dir(const char* path) { DWORD a = GetFileAttributesA(path); return (a != INVALID_FILE_ATTRIBUTES && (a & FILE_ATTRIBUTE_DIRECTORY)) || CreateDirectoryA(path, NULL) || GetLastError() == ERROR_ALREADY_EXISTS; }
static int config(char* out, size_t size, const char* leaf) { char root[PATH_SIZE], d[PATH_SIZE]; return wpm_get_data_root(root,sizeof(root)) && join(d,sizeof(d),root,"config") && dir(d) && join(out,size,d,leaf); }
static int trustdir(char* out, size_t size) { char root[PATH_SIZE]; return wpm_get_data_root(root,sizeof(root)) && join(out,size,root,"trust") && dir(out); }
static int read_all(const char* path, unsigned char** data, size_t* length) { FILE* f=fopen(path,"rb"); long n; if(!f) return 0; fseek(f,0,SEEK_END); n=ftell(f); rewind(f); if(n<0 || !( *data=(unsigned char*)malloc((size_t)n+1))) { fclose(f); return 0; } if(fread(*data,1,(size_t)n,f)!=(size_t)n){free(*data);fclose(f);return 0;} fclose(f); (*data)[n]=0; *length=(size_t)n; return 1; }
static int key_id(const unsigned char* public_key, char* out, size_t size) { unsigned char h[32]; if (size < KEY_ID_SIZE || sodium_init()<0 || crypto_generichash(h,sizeof(h),public_key,crypto_sign_PUBLICKEYBYTES,NULL,0)!=0) return 0; sodium_bin2hex(out,size,h,sizeof(h)); return 1; }
static int field(const char* text, const char* name, char* out, size_t size) { const char* p=strstr(text,name); size_t n; if(!p) return 0; p+=strlen(name); if(*p=='=') p++; n=strcspn(p,"\r\n\""); if(n==0 || n>=size) return 0; memcpy(out,p,n);out[n]=0;return 1; }
static int load_private(const char* path, unsigned char* secret) { unsigned char* text;size_t n;char b64[256];size_t out=0;int ok=0; if(!read_all(path,&text,&n))return 0; if(strstr((char*)text,"wpm-private-key-v1") && field((char*)text,"secret-key",b64,sizeof(b64)) && sodium_base642bin(secret,crypto_sign_SECRETKEYBYTES,b64,strlen(b64),NULL,&out,NULL,sodium_base64_VARIANT_ORIGINAL)==0 && out==crypto_sign_SECRETKEYBYTES)ok=1; sodium_memzero(text,n);free(text);return ok; }
static int load_public(const char* path, unsigned char* public_key) { unsigned char* text;size_t n,out=0;char b64[128];int ok=0; if(!read_all(path,&text,&n))return 0; if(strstr((char*)text,"wpm-public-key-v1") && field((char*)text,"public-key=",b64,sizeof(b64)) && sodium_base642bin(public_key,crypto_sign_PUBLICKEYBYTES,b64,strlen(b64),NULL,&out,NULL,sodium_base64_VARIANT_ORIGINAL)==0 && out==crypto_sign_PUBLICKEYBYTES)ok=1;free(text);return ok; }
static int write_private(const char* path,const unsigned char* key){char b64[sodium_base64_ENCODED_LEN(crypto_sign_SECRETKEYBYTES,sodium_base64_VARIANT_ORIGINAL)];FILE*f;if(GetFileAttributesA(path)!=INVALID_FILE_ATTRIBUTES)return 0;sodium_bin2base64(b64,sizeof(b64),key,crypto_sign_SECRETKEYBYTES,sodium_base64_VARIANT_ORIGINAL);f=fopen(path,"wb");if(!f)return 0;fprintf(f,"wpm-private-key-v1\nalgorithm=ed25519\nsecret-key=%s\n",b64);return fclose(f)==0;}
static int write_public(const char* path,const unsigned char* key){char b64[sodium_base64_ENCODED_LEN(crypto_sign_PUBLICKEYBYTES,sodium_base64_VARIANT_ORIGINAL)];FILE*f;if(GetFileAttributesA(path)!=INVALID_FILE_ATTRIBUTES)return 0;sodium_bin2base64(b64,sizeof(b64),key,crypto_sign_PUBLICKEYBYTES,sodium_base64_VARIANT_ORIGINAL);f=fopen(path,"wb");if(!f)return 0;fprintf(f,"wpm-public-key-v1\nalgorithm=ed25519\npublic-key=%s\n",b64);return fclose(f)==0;}

int wpm_set_default_key(const char* private_path){char full[PATH_SIZE],secret[crypto_sign_SECRETKEYBYTES],pub[crypto_sign_PUBLICKEYBYTES],id[KEY_ID_SIZE],path[PATH_SIZE];FILE*f;if(!GetFullPathNameA(private_path,sizeof(full),full,NULL)||!load_private(full,secret)) {printf("Error: invalid private key.\n");return 0;} memcpy(pub,secret+crypto_sign_SECRETKEYBYTES-crypto_sign_PUBLICKEYBYTES,crypto_sign_PUBLICKEYBYTES);if(!key_id(pub,id,sizeof(id))||!config(path,sizeof(path),"signing-key.txt")||(f=fopen(path,"w"))==NULL)return 0;fprintf(f,"path=%s\nkey-id=%s\n",full,id);fclose(f);sodium_memzero(secret,sizeof(secret));printf("Default signing key: %s\n",id);return 1;}
int wpm_clear_default_key(void){char path[PATH_SIZE];return config(path,sizeof(path),"signing-key.txt") && (DeleteFileA(path)||GetLastError()==ERROR_FILE_NOT_FOUND);}
int wpm_get_default_key(char* result,size_t size){char path[PATH_SIZE],*text;size_t n;int ok=0;if(!config(path,sizeof(path),"signing-key.txt")||!read_all(path,(unsigned char**)&text,&n))return 0;ok=field(text,"path",result,size);free(text);return ok;}
int wpm_keygen(const char* private_path,const char* public_path,int make_default){unsigned char pub[crypto_sign_PUBLICKEYBYTES],sec[crypto_sign_SECRETKEYBYTES];char id[KEY_ID_SIZE];if(sodium_init()<0||crypto_sign_keypair(pub,sec)!=0||!write_private(private_path,sec)||!write_public(public_path,pub)){printf("Error: could not generate key pair.\n");sodium_memzero(sec,sizeof(sec));return 0;}key_id(pub,id,sizeof(id));sodium_memzero(sec,sizeof(sec));printf("Generated key ID: %s\nPublic key: %s\n",id,public_path);return !make_default||wpm_set_default_key(private_path);}
int wpm_trust_add(const char* public_path){unsigned char pub[crypto_sign_PUBLICKEYBYTES];char id[KEY_ID_SIZE],d[PATH_SIZE],p[PATH_SIZE];if(!load_public(public_path,pub)||!key_id(pub,id,sizeof(id))||!trustdir(d,sizeof(d))||snprintf(p,sizeof(p),"%s\\%s.pub",d,id)<0)return 0;if(GetFileAttributesA(p)!=INVALID_FILE_ATTRIBUTES){printf("Error: key is already trusted or revoked.\n");return 0;}if(!write_public(p,pub))return 0;printf("Trusted key: %s\n",id);return 1;}
int wpm_trust_list(void){char d[PATH_SIZE],s[PATH_SIZE];WIN32_FIND_DATAA e;HANDLE h;if(!trustdir(d,sizeof(d))||!join(s,sizeof(s),d,"*.pub"))return 0;h=FindFirstFileA(s,&e);if(h==INVALID_HANDLE_VALUE){printf("No trusted keys.\n");return 1;}do{char id[KEY_ID_SIZE];strncpy_s(id,sizeof(id),e.cFileName,64);printf("%s active\n",id);}while(FindNextFileA(h,&e));FindClose(h);return 1;}
int wpm_trust_revoke(const char* id){char d[PATH_SIZE],p[PATH_SIZE],r[PATH_SIZE];if(strlen(id)!=64||!trustdir(d,sizeof(d))||snprintf(p,sizeof(p),"%s\\%s.pub",d,id)<0||snprintf(r,sizeof(r),"%s\\%s.revoked",d,id)<0||GetFileAttributesA(p)==INVALID_FILE_ATTRIBUTES){printf("Error: trusted key not found: %s\n",id);return 0;}if(!MoveFileExA(p,r,MOVEFILE_REPLACE_EXISTING))return 0;printf("Revoked key: %s\n",id);return 1;}
int wpm_sign_package_index(const char* source,const char* private_path){char index[PATH_SIZE],sigpath[PATH_SIZE],id[KEY_ID_SIZE],b64[sodium_base64_ENCODED_LEN(crypto_sign_BYTES,sodium_base64_VARIANT_ORIGINAL)],pub64[sodium_base64_ENCODED_LEN(crypto_sign_PUBLICKEYBYTES,sodium_base64_VARIANT_ORIGINAL)];unsigned char sec[crypto_sign_SECRETKEYBYTES],pub[crypto_sign_PUBLICKEYBYTES],signature[crypto_sign_BYTES],*data;size_t n;unsigned long long slen;FILE*f;if(!private_path||!private_path[0])return 1;if(!join(index,sizeof(index),source,".wpm\\index.csv")||!join(sigpath,sizeof(sigpath),source,".wpm\\signature.json")||!load_private(private_path,sec)||!read_all(index,&data,&n)){printf("Error: could not sign package index.\n");return 0;}memcpy(pub,sec+crypto_sign_SECRETKEYBYTES-crypto_sign_PUBLICKEYBYTES,sizeof(pub));if(!key_id(pub,id,sizeof(id))||crypto_sign_detached(signature,&slen,data,(unsigned long long)n,sec)!=0){free(data);sodium_memzero(sec,sizeof(sec));return 0;}sodium_bin2base64(b64,sizeof(b64),signature,sizeof(signature),sodium_base64_VARIANT_ORIGINAL);sodium_bin2base64(pub64,sizeof(pub64),pub,sizeof(pub),sodium_base64_VARIANT_ORIGINAL);f=fopen(sigpath,"wb");if(!f){free(data);sodium_memzero(sec,sizeof(sec));return 0;}fprintf(f,"{\n  \"version\": 1,\n  \"algorithm\": \"ed25519\",\n  \"key_id\": \"%s\",\n  \"public_key\": \"%s\",\n  \"signature\": \"%s\"\n}\n",id,pub64,b64);fclose(f);free(data);sodium_memzero(sec,sizeof(sec));return 1;}
int wpm_validate_package_signature(const char* stage,int allow,char* unused,size_t unused_size){char sigp[PATH_SIZE],index[PATH_SIZE],id[KEY_ID_SIZE],declared_id[KEY_ID_SIZE],b64[256],pub64[128],d[PATH_SIZE],pubp[PATH_SIZE],rev[PATH_SIZE],answer[16];unsigned char* text=NULL,*data=NULL,pub[crypto_sign_PUBLICKEYBYTES],sig[crypto_sign_BYTES];size_t n,sl=0,pl=0;int known;if(unused&&unused_size)unused[0]=0;if(!join(sigp,sizeof(sigp),stage,".wpm\\signature.json"))return 0;if(GetFileAttributesA(sigp)==INVALID_FILE_ATTRIBUTES){if(allow){printf("Warning: installing unsigned package.\n");return 1;}printf("Error: unsigned packages are not allowed.\n");return 0;}if(!read_all(sigp,&text,&n)||!field((char*)text,"\"key_id\": \"",id,sizeof(id))||!field((char*)text,"\"public_key\": \"",pub64,sizeof(pub64))||!field((char*)text,"\"signature\": \"",b64,sizeof(b64))||strlen(id)!=64||!join(index,sizeof(index),stage,".wpm\\index.csv")||!read_all(index,&data,&n)||!trustdir(d,sizeof(d))||snprintf(pubp,sizeof(pubp),"%s\\%s.pub",d,id)<0||snprintf(rev,sizeof(rev),"%s\\%s.revoked",d,id)<0||GetFileAttributesA(rev)!=INVALID_FILE_ATTRIBUTES||sodium_base642bin(pub,sizeof(pub),pub64,strlen(pub64),NULL,&pl,NULL,sodium_base64_VARIANT_ORIGINAL)!=0||pl!=sizeof(pub)){printf("Error: package signature validation failed.\n");goto fail;}strcpy_s(declared_id,sizeof(declared_id),id);known=GetFileAttributesA(pubp)!=INVALID_FILE_ATTRIBUTES;if(known&&!load_public(pubp,pub)){printf("Error: package signature validation failed.\n");goto fail;}if(!key_id(pub,id,sizeof(id))||_stricmp(id,declared_id)!=0||sodium_base642bin(sig,sizeof(sig),b64,strlen(b64),NULL,&sl,NULL,sodium_base64_VARIANT_ORIGINAL)!=0||sl!=sizeof(sig)||crypto_sign_verify_detached(sig,data,(unsigned long long)n,pub)!=0){printf("Error: package signature validation failed.\n");goto fail;}if(!known){printf("Package signing key %s is not trusted. Trust it? [y/N]: ",declared_id);if(!fgets(answer,sizeof(answer),stdin)||(tolower((unsigned char)answer[0])!='y')){printf("Error: signing key was not trusted.\n");goto fail;}if(!write_public(pubp,pub)){printf("Error: could not trust signing key.\n");goto fail;}printf("Trusted key: %s\n",declared_id);}free(text);free(data);return 1;fail:if(text)free(text);if(data)free(data);return 0;}
